In [0]:
print("hello world")

hello world

# Step 1: Load the Dataset

In this step, the Superstore dataset is uploaded to Databricks and loaded into a Pandas DataFrame for further exploration and cleaning.

In [0]:
# Import Pandas
import pandas as pd

# Load the dataset
df = pd.read_csv("/Workspace/Users/ridamagrawal01@gmail.com/Sample - Superstore.csv", encoding="latin1")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [0]:
df.head()

   Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0       1  CA-2016-152156   11/8/2016  ...        2     0.00   41.9136
1       2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
2       3  CA-2016-138688   6/12/2016  ...        2     0.00    6.8714
3       4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
4       5  US-2015-108966  10/11/2015  ...        2     0.20    2.5164

[5 rows x 21 columns]

In [0]:
print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows : 9994
Number of Columns : 21

# Step 2: Explore the Dataset

The dataset is explored to understand its structure, dimensions, column names, data types, and basic statistical information before performing any data cleaning.

In [0]:
# Display first 5 rows
df.head()

   Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0       1  CA-2016-152156   11/8/2016  ...        2     0.00   41.9136
1       2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
2       3  CA-2016-138688   6/12/2016  ...        2     0.00    6.8714
3       4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
4       5  US-2015-108966  10/11/2015  ...        2     0.20    2.5164

[5 rows x 21 columns]

In [0]:
# Display last 5 rows
df.tail()

      Row ID        Order ID Order Date  ... Quantity Discount   Profit
9989    9990  CA-2014-110422  1/21/2014  ...        3      0.2   4.1028
9990    9991  CA-2017-121258  2/26/2017  ...        2      0.0  15.6332
9991    9992  CA-2017-121258  2/26/2017  ...        2      0.2  19.3932
9992    9993  CA-2017-121258  2/26/2017  ...        4      0.0  13.3200
9993    9994  CA-2017-119914   5/4/2017  ...        2      0.0  72.9480

[5 rows x 21 columns]

In [0]:
# Number of rows and columns
print("Dataset Shape:", df.shape)

Dataset Shape: (9994, 21)

In [0]:
# List all column names
print("Columns in the dataset:")
print(df.columns.tolist())

Columns in the dataset:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [0]:
# Display data types
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [0]:
# Display complete dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [0]:
# Statistical summary of numerical columns
df.describe()

            Row ID   Postal Code  ...     Discount       Profit
count  9994.000000   9994.000000  ...  9994.000000  9994.000000
mean   4997.500000  55190.379428  ...     0.156203    28.656896
std    2885.163629  32063.693350  ...     0.206452   234.260108
min       1.000000   1040.000000  ...     0.000000 -6599.978000
25%    2499.250000  23223.000000  ...     0.000000     1.728750
50%    4997.500000  56430.500000  ...     0.200000     8.666500
75%    7495.750000  90008.000000  ...     0.200000    29.364000
max    9994.000000  99301.000000  ...     0.800000  8399.976000

[8 rows x 6 columns]

In [0]:
# Memory usage of the dataset
memory = df.memory_usage(deep=True).sum() / 1024**2
print(f"Memory Usage: {memory:.2f} MB")

Memory Usage: 9.21 MB

# Step 3: Handle Missing Values

In this step, the dataset is checked for missing (null) values. If any missing values are found, appropriate cleaning techniques such as filling or dropping them can be applied.

In [0]:
# Check missing values in each column
missing_values = df.isnull().sum()

print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [0]:
# Total missing values
total_missing = df.isnull().sum().sum()

print(f"Total Missing Values: {total_missing}")

Total Missing Values: 0

In [0]:
# Percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Percentage of Missing Values:")
print(missing_percentage)

Percentage of Missing Values:
Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
Quantity         0.0
Discount         0.0
Profit           0.0
dtype: float64

In [0]:
if total_missing > 0:
    df = df.dropna()
    print("Missing values removed.")
else:
    print("No missing values found. Dataset is already clean.")

No missing values found. Dataset is already clean.

In [0]:
empty_rows = df.isnull().all(axis=1).sum()

print(f"Completely Empty Rows: {empty_rows}")

Completely Empty Rows: 0

In [0]:
df.dropna()

      Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0          1  CA-2016-152156   11/8/2016  ...        2     0.00   41.9136
1          2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
2          3  CA-2016-138688   6/12/2016  ...        2     0.00    6.8714
3          4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
4          5  US-2015-108966  10/11/2015  ...        2     0.20    2.5164
...      ...             ...         ...  ...      ...      ...       ...
9989    9990  CA-2014-110422   1/21/2014  ...        3     0.20    4.1028
9990    9991  CA-2017-121258   2/26/2017  ...        2     0.00   15.6332
9991    9992  CA-2017-121258   2/26/2017  ...        2     0.20   19.3932
9992    9993  CA-2017-121258   2/26/2017  ...        4     0.00   13.3200
9993    9994  CA-2017-119914    5/4/2017  ...        2     0.00   72.9480

[9994 rows x 21 columns]

# Filter records where Category is Furniture
furniture_df = df[df["Category"] == "Furniture"]

print("Number of Furniture Records:", furniture_df.shape[0])
furniture_df.head()

In [0]:
# Filter records where Category is Furniture
furniture_df = df[df["Category"] == "Furniture"]

print("Number of Furniture Records:", furniture_df.shape[0])
furniture_df.head()

Number of Furniture Records: 2121

    Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0        1  CA-2016-152156   11/8/2016  ...        2     0.00   41.9136
1        2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
3        4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
5        6  CA-2014-115812    6/9/2014  ...        7     0.00   14.1694
10      11  CA-2014-115812    6/9/2014  ...        9     0.20   85.3092

[5 rows x 21 columns]

In [0]:
# Filter orders with Sales greater than 500
high_sales_df = df[df["Sales"] > 500]

print("Orders with Sales > 500:", high_sales_df.shape[0])
high_sales_df.head()

Orders with Sales > 500: 1162

    Row ID        Order ID  Order Date  ... Quantity Discount    Profit
1        2  CA-2016-152156   11/8/2016  ...        3     0.00  219.5820
3        4  US-2015-108966  10/11/2015  ...        5     0.45 -383.0310
7        8  CA-2014-115812    6/9/2014  ...        6     0.20   90.7152
10      11  CA-2014-115812    6/9/2014  ...        9     0.20   85.3092
11      12  CA-2014-115812    6/9/2014  ...        4     0.20   68.3568

[5 rows x 21 columns]

In [0]:
# Filter orders with Profit greater than 100
high_profit_df = df[df["Profit"] > 100]

print("Orders with Profit > 100:", high_profit_df.shape[0])
high_profit_df.head()

Orders with Profit > 100: 890

    Row ID        Order ID  Order Date  ... Quantity Discount    Profit
1        2  CA-2016-152156   11/8/2016  ...        3      0.0  219.5820
13      14  CA-2016-161389   12/5/2016  ...        3      0.2  132.5922
24      25  CA-2015-106320   9/25/2015  ...        3      0.0  240.2649
35      36  CA-2016-117590   12/8/2016  ...        7      0.2  123.4737
54      55  CA-2016-105816  12/11/2016  ...        5      0.0  298.6855

[5 rows x 21 columns]

In [0]:
selected_columns = df[[
    "Order ID",
    "Customer Name",
    "Category",
    "Sub-Category",
    "Sales",
    "Quantity",
    "Profit"
]]

selected_columns.head()

         Order ID    Customer Name  ... Quantity    Profit
0  CA-2016-152156      Claire Gute  ...        2   41.9136
1  CA-2016-152156      Claire Gute  ...        3  219.5820
2  CA-2016-138688  Darrin Van Huff  ...        2    6.8714
3  US-2015-108966   Sean O'Donnell  ...        5 -383.0310
4  US-2015-108966   Sean O'Donnell  ...        2    2.5164

[5 rows x 7 columns]

In [0]:
top_sales = df.sort_values(by="Sales", ascending=False)

top_sales.head(10)

      Row ID        Order ID  Order Date  ... Quantity Discount     Profit
2697    2698  CA-2014-145317   3/18/2014  ...        6      0.5 -1811.0784
6826    6827  CA-2016-118689   10/2/2016  ...        5      0.0  8399.9760
8153    8154  CA-2017-140151   3/23/2017  ...        4      0.0  6719.9808
2623    2624  CA-2017-127180  10/22/2017  ...        4      0.2  3919.9888
4190    4191  CA-2017-166709  11/17/2017  ...        3      0.0  5039.9856
9039    9040  CA-2016-117121  12/17/2016  ...       13      0.0  4946.3700
4098    4099  CA-2014-116904   9/23/2014  ...        5      0.0  4630.4755
4277    4278  US-2016-107440   4/16/2016  ...        7      0.0  2365.9818
8488    8489  CA-2016-158841    2/2/2016  ...        5      0.0  2799.9840
6425    6426  CA-2016-143714   5/23/2016  ...        4      0.4  1119.9968

[10 rows x 21 columns]

In [0]:
best_orders = df[
    (df["Sales"] > 500) &
    (df["Profit"] > 50)
]

best_orders.head()

    Row ID        Order ID Order Date  ... Quantity Discount    Profit
1        2  CA-2016-152156  11/8/2016  ...        3      0.0  219.5820
7        8  CA-2014-115812   6/9/2014  ...        6      0.2   90.7152
10      11  CA-2014-115812   6/9/2014  ...        9      0.2   85.3092
11      12  CA-2014-115812   6/9/2014  ...        4      0.2   68.3568
24      25  CA-2015-106320  9/25/2015  ...        3      0.0  240.2649

[5 rows x 21 columns]

# Step 5: Remove Duplicate Records

Duplicate records can affect data analysis and lead to incorrect results. In this step, the dataset is checked for duplicate rows and duplicate records are removed if present.

In [0]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Number of Duplicate Records: {duplicate_count}")

Number of Duplicate Records: 0

In [0]:
# Store dataset shape before removing duplicates
rows_before = df.shape[0]

print("Rows before removing duplicates:", rows_before)

Rows before removing duplicates: 9994

In [0]:
# Remove duplicate rows
df = df.drop_duplicates()

print("Duplicate records removed successfully.")

Duplicate records removed successfully.

In [0]:
rows_after = df.shape[0]

print("Rows after removing duplicates:", rows_after)
print("Duplicates Remaining:", df.duplicated().sum())

Rows after removing duplicates: 9994
Duplicates Remaining: 0

In [0]:
removed_rows = rows_before - rows_after

print(f"Total Duplicate Rows Removed: {removed_rows}")

Total Duplicate Rows Removed: 0

In [0]:
df.drop_duplicates(inplace=True)

In [0]:
# Create Price column
df["Price"] = df["Sales"] / df["Quantity"]

# Create total_amount column
df["total_amount"] = df["Price"] * df["Quantity"]

# Display the new columns
df[["Sales", "Quantity", "Price", "total_amount"]].head()

      Sales  Quantity     Price  total_amount
0  261.9600         2  130.9800      261.9600
1  731.9400         3  243.9800      731.9400
2   14.6200         2    7.3100       14.6200
3  957.5775         5  191.5155      957.5775
4   22.3680         2   11.1840       22.3680

In [0]:
spark_df = spark.createDataFrame(df)

In [0]:
df.to_csv("cleaned_superstore.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

# Summary

In this assignment:

- Loaded the Superstore dataset into a Pandas DataFrame.
- Explored the dataset using head(), tail(), shape, columns, data types, info(), and describe().
- Checked for missing values and verified data quality.
- Filtered rows and selected important columns.
- Removed duplicate records.
- Created derived columns (`Price` and `total_amount`).
- Saved the cleaned dataset as a new CSV file.
- Additionally stored the cleaned dataset as a Delta Table in Databricks and viewed its version history, demonstrating Delta Lake concepts such as ACID transactions and versioning.